import streamlit as st

st.header("2,400 PHP. Kaya ba?")
st.title("A study on the Philippine Poverty Threshold and its Factors")
st.caption('Presented By: Group 2 | Hungry Sleepers')

st.subheader("Introduction")
st.image("images/5.png")
st.subheader("Objectives")
st.image("images/8.png")
st.subheader("Preprocessing")
st.image("images/10.png")
st.image("images/11.png")
# st.header("Exploratory Data Analysis")
# st.image("images/13.png")
# st.image("images/14.png")
# st.image("images/15.png")
# st.subheader("Main Metric")
# st.image("images/16.png")
# st.subheader("Modelling Pipeline")
# st.image("images/17.png")
# st.image("images/18.png")
# st.image("images/21.png")
# st.image("images/22.png")
# st.image("images/23.png")
# st.image("images/24.png")

# st.title("Results and Discussion")
# st.subheader("Utilize the best model in identifying the key factors influencing the Under the Poverty line households")
# st.image("images/31.png")

# st.subheader("Evaluate and potentially challenge the poverty threshold (in pesos/person) set by the PSA")
# st.image("images/33.png")
# st.image("images/34.png")
# st.image("images/35.png")
# st.image("images/36.png")

# st.title("Conclusion")
# st.image("images/37.png")
